### ISSUE TITLE
Why do you collect code in a single bundle?

### ISSUE THREAD

**Issue by retyui** [d3/d3-shape#121]
**Is your feature request related to a problem? Please describe.**
I try reduce my bundels size. In my project I use some imports:
```js
import { area } from 'd3-shape';
```
I would like to have the opportunity to do so:
```js
import area from 'd3-shape/lib/area';
```

**Describe the solution you'd like**
Why do you collect code in a single js bundle?
Use flatten struct!
Like as: `lodash-es`, `date-fns`, `react-router`, `ramda`, `recompose`

**Comment by mbostock** [comment]
The D3 modules include UMD bundles for convenient consumption in browsers either as vanilla script tags or via require (AMD).

If you are in an environment that supports ES modules, you shouldn’t be using the UMD bundle. You should configure your environment (such as your bundler) to consume the `module` entry point ([index.js](https://github.com/d3/d3-shape/blob/master/index.js)) rather than the `main` entry point.

If you use a tree-shaking bundler such as Rollup or Webpack, the bundler should automatically prune unused code, so you don’t need to import from the source files directly.

In general, I don’t provide support for people’s bundlers and environments, since they vary so widely and I’m not familiar with all of them. So if you have further questions, please consider using Stack Overflow rather than posting an issue here. Thank you!

**Comment by retyui** [comment]
If a **tree-shaking**  worked, then why did these plugins appear:
![npm lodash-webpack-plugin](https://img.shields.io/npm/dm/lodash-webpack-plugin.svg) [lodash-webpack-plugin](https://www.npmjs.com/package/lodash-webpack-plugin) 
![npm babel-plugin-lodash](https://img.shields.io/npm/dm/babel-plugin-lodash.svg) [babel-plugin-lodash](https://www.npmjs.com/package/babel-plugin-lodash) 
![npm babel-plugin-transform-imports](https://img.shields.io/npm/dm/babel-plugin-transform-imports.svg) [babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports) 
![npm babel-plugin-date-fns](https://img.shields.io/npm/dm/babel-plugin-date-fns.svg) [babel-plugin-date-fns](https://www.npmjs.com/package/babel-plugin-date-fns) 
I can help you add the ES version to the build process!

**Comment by retyui** [comment]
## 1) Direct import
```js
import area from 'd3-shape/src/area';
console.log(area());
```
### Result:
```
Version: webpack 4.8.3
Time: 654ms
Built at: 2018-05-24 23:03:51
  Asset      Size  Chunks             Chunk Names
main.js  4.96 KiB       0  [emitted]  main
```

--------------------------------------
## 2) Indirect import
```js
import { area } from 'd3-shape';
console.log(area());
```
### Result:
```
Version: webpack 4.8.3
Time: 502ms
Built at: 2018-05-24 23:06:06
  Asset      Size  Chunks             Chunk Names
main.js  18.7 KiB       0  [emitted]  main
```

The difference is 4 times greater!!!

**Comment by amenadiel** [comment]
@mbostock I gave it a try and he's right. Generating an es6 module with rollup importing {area} from index

```js
import {area} from './index.js';
export default area;
```

results in a 15kb module, whereas 

import area from './src/area.js';
export default area;
```
creates e 9kb mofule


the former brings along the definitions for MonotoneX and MonotoneY which are not used. I can't see why. Perthaps rollup has a bug when determining tree shaking?

**Comment by retyui** [comment]
@mbostock 
@amenadiel 
A good idea is to use this plugin [annotate-pure-calls](https://github.com/Andarist/babel-plugin-annotate-pure-calls)
This helps with 'tree-shaking' curried entry point. Works similar to sideEffects field in pkg.json, only sideEffects targets webpack@4+ and #__PURE__ comments target uglifyJS

**Comment by amenadiel** [comment]
I only get those #PURE comments when I do (for example) `import * as d3 from 'd3-selection`. Which also freezes the object. 

BTW, doing that also exports `event` as a getter. For example, using

```js
import * as d3 from 'd3-selection';
export default d3;
```

results in a module that ends with:

```js
var d3 = /*#__PURE__*/Object.freeze({
create: create,
creator: creator,
local: local,
matcher: matcher$1,
mouse: mouse,
namespace: namespace,
namespaces: namespaces,
clientPoint: point,
select: select,
selectAll: selectAll,
selection: selection,
selector: selector,
selectorAll: selectorAll,
style: styleValue,
touch: touch,
touches: touches,
window: defaultView,
get event () { return event; },
customEvent: customEvent
});

export default d3;
```

I'm missing something here :slightly_smiling_face: 

BTW @mbostock I see no harm in building an es6 module into the `dist` folder that finished with

```js
export { arc,
 area,
 line,
 pie,
 areaRadial,
 areaRadial as radialArea,
 lineRadial$1 as lineRadial,
 lineRadial$1 as radialLine,
 pointRadial,
 linkHorizontal,
 linkVertical,
 linkRadial,
 symbol,
 symbols,
 circle as symbolCircle,
 cross as symbolCross,
 diamond as symbolDiamond,
 square as symbolSquare,
 star as symbolStar,
 triangle as symbolTriangle,
 wye as symbolWye,
 basisClosed as curveBasisClosed,
 basisOpen as curveBasisOpen,
 basis as curveBasis,
 bundle as curveBundle,
 cardinalClosed as curveCardinalClosed,
 cardinalOpen as curveCardinalOpen,
 cardinal as curveCardinal,
 catmullRomClosed as curveCatmullRomClosed,
 catmullRomOpen as curveCatmullRomOpen,
 catmullRom as curveCatmullRom,
 linearClosed as curveLinearClosed,
 curveLinear,
 monotoneX as curveMonotoneX,
 monotoneY as curveMonotoneY,
 natural as curveNatural,
 step as curveStep,
 stepAfter as curveStepAfter,
 stepBefore as curveStepBefore,
 stack,
 expand as stackOffsetExpand,
 diverging as stackOffsetDiverging,
 none as stackOffsetNone,
 silhouette as stackOffsetSilhouette,
 wiggle as stackOffsetWiggle,
 ascending as stackOrderAscending,
 descending$1 as stackOrderDescending,
 insideOut as stackOrderInsideOut,
 none$1 as stackOrderNone,
 reverse as stackOrderReverse 
};
```

because, even if it's trivial to import components from `d3-shape/index.js` it isn't trivial to do so importing from `d3/index.js` since you don't really know where do each export come from. So, for the main `d3` package, it would be nice to have an es6 module in `dist` listing every export as

```js
export { version,
 bisectRight as bisect,
 bisectRight,
 bisectLeft,
 ascending,
 bisector,
 cross,
 descending,
 deviation,
 extent,
 histogram,
 freedmanDiaconis as thresholdFreedmanDiaconis,
 scott as thresholdScott,
 thresholdSturges,
 max,
 mean,
 median,
 merge,
 min,
 pairs,
 permute,
 threshold as quantile,
 sequence as range,
 scan,
 shuffle,
 sum,
 ticks,
 tickIncrement,
 tickStep,
 transpose,
 variance,
 zip,
 axisTop,
 axisRight,
 axisBottom,
 axisLeft,
 brush,
 brushX,
 brushY,
 brushSelection,
 chord,
 ribbon,
 ....
  now,
 timer,
 timerFlush,
 timeout$1 as timeout,
 interval$1 as interval,
 transition,
 active,
 interrupt,
 voronoi,
 zoom,
 transform$1 as zoomTransform,
 identity$8 as zoomIdentity 
};
```

because it would make so much easier to import just needed methods without digging into d3 componets to find out where do each of them come from.

However, this is just a loosely related opinion regarding this issue in particular, so you might as well disregard it.
