### ISSUE TITLE
padAngle allows data that includes 0 angle to fill

### ISSUE THREAD

**Issue by dvnrsn** [d3/d3-shape#128]
https://codepen.io/devcon/pen/qMERrW

If there is data that includes a 0, the last padAngle is filled with a sliver. Is this expected behavior?

**Comment by curran** [comment]
What is the expected behavior?

Here's what I notice with your example:

`data = [1, 1, 2, 3, 5, 8, 13];`

![image](https://user-images.githubusercontent.com/68416/67376782-54ef8080-f5a2-11e9-805a-8d5eef573a32.png)

`data = [0, 1, 1, 2, 3, 5, 8, 13];`

![image](https://user-images.githubusercontent.com/68416/67376846-6afd4100-f5a2-11e9-91f9-ceed2458d682.png)

`data = [0, 0, 1, 1, 2, 3, 5, 8, 13];`

![image](https://user-images.githubusercontent.com/68416/67376899-7f413e00-f5a2-11e9-8f64-fde76efa258d.png)

The thing that doesn't make sense to me is that if there are multiple zeroes, there's still only one sliver.

Possible options to solve this:

 * Do not produce any slivers (filter out zero values within the layout)
 * Introduce multiple slivers for multiple zeroes
 * Just leave it as-is and expect developers to filter out zeroes before using the layout

Which one would be preferable?

**Comment by dvnrsn** [comment]
Do not produce any slivers I'd say

**Comment by mbostock** [comment]
The problem here is that you’re using [*arc*.padAngle](https://github.com/d3/d3-shape/blob/master/README.md#arc_padAngle), but as the documentation suggests, you should be using [*pie*.padAngle](https://github.com/d3/d3-shape/blob/master/README.md#pie_padAngle) instead. This gives you multiple slivers for multiple zeroes:

![image](https://user-images.githubusercontent.com/230541/68999639-074ff600-0878-11ea-8b42-71fa9a2a68c2.png)

This can’t be fixed at the *arc*.padAngle level because there that padding is subtracted from the arc, and if the arc is zero-angle, there’s nothing to subtract from.
