### ISSUE TITLE
Monotone curves which are monotonic in y, not x?

### ISSUE THREAD

**Issue by xile611** [d3/d3-shape#57]
Do you have any plan to support line generator of data which is sorted by y-value ?

**Comment by mbostock** [comment]
Sorted by *y*-value, or not sorted by *x*-value? If you are you asking whether the line generator should automatically sort the input the *x*-value, the answer is definitely no because there are some cases where you don’t want this behavior.

However, I could see it being useful to have a *line*.sort accessor which defaults to null, and lets you specify a comparator. If the comparator is specified, the data would be sorted using the specified comparator before the points were generated and passed to the curve. (I could also imagine a sortX or sortY accessor which sorts on the computed points, but then you’d have to buffer the points and it’d be a bit more work, and I think sorting the data is probably more sufficient.)

The line generator would need to sort a copy of the data, though, so as to avoid modifying the input. So even if we added this, it’d probably be better if the caller sorted the data before passing it to the line generator. So, I guess I’m inclined to not add this feature since it perhaps encourages inefficient code.

**Comment by xile611** [comment]
Sorry, my question was not clearly stated.
   You can look at the image below, I just want to draw a line of "vertical layout" which is generated by points sorted by y-value.
   And I use d3.line with the curve factory  d3.curveMonotone. The the result line is strange. So I want to know do you have any plan to support this kind of line?
 
![Vertical Line](http://7xqkgx.com1.z1.glb.clouddn.com/vertical%20line.png)

**Comment by mbostock** [comment]
Okay, so your query is specifically in regards to [curveMonotone](https://github.com/d3/d3-shape#curveMonotone), then, which “[assumes] that the input data is monotonic in *x*.”

We could have distinct curveMonotoneX and curveMonotoneY that are equivalent except one requires monotonicity in *x* while the other requires monotonicity in *y*.

You can also workaround this restriction by switching the *x* and *y* of your line as input to the line generator, and then transform the resulting output (using an SVG or Canvas transform) by reflecting over the y=x line. But that’s a bit tedious.

**Comment by mbostock** [comment]
Fixed in 0.5.
